# This source file is subject to the (Open Source Initiative) BSD license
# that is bundled with this package in the LICENSE file. It is also available
# through the world-wide-web at this URL: http://www.ontic.com.au/license.html
# If you did not receive a copy of the license and are unable to obtain it through
# the world-wide-web, please send an email to license@ontic.com.au immediately.
# Copyright (c) 2010-2016 Ontic. (http://www.ontic.com.au). All rights reserved.

---

- name: 'Git | Configure system Git config file.'
  become: yes
  template:
    src: 'system.gitconfig.j2'
    dest: '/etc/gitconfig'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: '{{ git_config | default(None) != None }}'

- name: 'Git | Configure absent Git config files.'
  become: yes
  file:
    path: '/home/{{ item.username }}/.gitconfig'
    state: 'absent'
  with_items: '{{ git_users }}'
  when: '{{ git_users | default(None) != None and item.state | default("present") == "absent" }}'

- name: 'Git | Configure present Git user config files.'
  become: yes
  template:
    src: 'user.gitconfig.j2'
    dest: '/home/{{ item.username }}/.gitconfig'
    owner: '{{ item.username }}'
    group: '{{ item.group | default(item.username) }}'
    mode:  '{{ item.mode | default(0644) }}'
  with_items: '{{ git_users }}'
  when: '{{ git_users | default(None) != None and item.state | default("present") == "present" }}'