# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'Git | Include OS-specific variables.'
  include_vars: '{{ ansible_os_family }}.yml'
  tags:
    - 'git'
    - 'git-package'
    - 'git-configure'
    - 'package'
    - 'configure'

- name: 'Git | Define Git packages.'
  set_fact:
    git_packages: '{{ git_default_packages }}'
  when: 'not git_packages'
  tags:
    - 'git'
    - 'git-package'
    - 'git-configure'
    - 'package'
    - 'configure'

- import_tasks: 'package.yml'
  tags:
    - 'git'
    - 'git-package'
    - 'package'

- import_tasks: 'configure.yml'
  tags:
    - 'git'
    - 'git-configure'
    - 'configure'